version: '4.35'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      DEBUG: "${DEBUG}"
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  db:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - backend_network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
        - backend_network

volumes:
  postgres_data:
  redis_data:

networks:
  backend_network: