version: '4.35'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh start.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    depends_on:
      - db
      - redis

  db:
    image: postgres:17.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:latest

volumes:
  postgres_data:
  redis_data: