# Generated by Django 5.1.2 on 2024-12-14 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_admins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(related_name='company_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
