name: Django CI

on:
  push: {}
  pull_request: {}

jobs:
  QuizBackendCI:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:17.0
        env:
          POSTGRES_DB: "${{ secrets.DATABASE_NAME }}"
          POSTGRES_USER: "${{ secrets.DATABASE_USER }}"
          POSTGRES_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
        ports:
          - "5432:5432"

      redis:
        image: redis:latest
        ports:
          - "6379:6379"


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        env:
          DATABASE_HOST: "${{ secrets.DATABASE_HOST }}"
          DATABASE_PORT: "${{ secrets.DATABASE_PORT }}"
        run: |
          until pg_isready -h "${{ secrets.DATABASE_HOST }}" -p "${{ secrets.DATABASE_PORT }}"; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Apply unapplied migrations
        env:
          DJANGO_SETTINGS_MODULE: quiz_backend.settings
          DATABASE_ENGINE: django.db.backends.postgresql
          DATABASE_NAME: "${{ secrets.DATABASE_NAME }}"
          DATABASE_USER: "${{ secrets.DATABASE_USER }}"
          DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
          DATABASE_HOST: "${{ secrets.DATABASE_HOST }}"
          DATABASE_PORT: "${{ secrets.DATABASE_PORT }}"
          SECRET_KEY: "${{ secrets.SECRET_KEY }}"
          DEBUG: 1
          REDIS_HOST: "${{ secrets.REDIS_HOST }}"
          REDIS_PORT: "${{ secrets.REDIS_PORT }}"
          CACHES_ENGINE: "${{ secrets.CACHES_ENGINE }}"
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Run linter (Ruff)
        run: ruff check .

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: quiz_backend.settings
          DATABASE_ENGINE: django.db.backends.postgresql
          DATABASE_NAME: "${{ secrets.DATABASE_NAME }}"
          DATABASE_USER: "${{ secrets.DATABASE_USER }}"
          DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"
          DATABASE_HOST: "${{ secrets.DATABASE_HOST }}"
          DATABASE_PORT: "${{ secrets.DATABASE_PORT }}"
          SECRET_KEY: "${{ secrets.SECRET_KEY }}"
          DEBUG: 1
          REDIS_HOST: "${{ secrets.REDIS_HOST }}"
          REDIS_PORT: "${{ secrets.REDIS_PORT }}"
          CACHES_ENGINE: "${{ secrets.CACHES_ENGINE }}"
        run: python manage.py test

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
